apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shlink-ingress-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shlink-ingress-controller.labels" . | nindent 4 }}
